version: "3.8"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.8
    container_name: kafka
#    ports:
#      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - linkedin-network
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  
  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8090-8090"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_KSQLDBSERVER: http://ksqldb0:8080

  notification-db:
    image: postgres
    container_name: notification-db
    environment:
      - POSTGRES_DB=notificationDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Manoj@123
    networks:
      - linkedin-network
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  post-db:
    image: postgres
    container_name: posts-db
    environment:
      - POSTGRES_DB=postsDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Manoj@123
    networks:
      - linkedin-network
    volumes:
      - posts-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_DB=usersDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Manoj@123
    networks:
      - linkedin-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  connections-db:
    image: neo4j
    container_name: connections-db
    environment:
      - NEO4J_AUTH=neo4j/password   #Set your username and password
    ports:
      - "7474:7474"   #HTTP ports
      - "7687:7687"   #Bolt port
    volumes:
      - connections-db-data:/data   #Persist data
    networks:
      - linkedin-network

  discovery-server:
    image: shivmanoj/linkedin-app/discovery-server
    container_name: discovery-server
    networks:
      - linkedin-network
    ports:
      - "8761:8761"

  notification-service:
    image: shivmanoj/linkedin-app/notification-service
    container_name: notification-service
    networks:
      - linkedin-network
    depends_on:
      - notification-db
      - discovery-server
      - kafka

  post-service:
    image: shivmanoj/linkedin-app/post-service
    container_name: post-service
    networks:
      - linkedin-network
    depends_on:
      - post-db
      - discovery-server
      - kafka

  user-service:
    image: shivmanoj/linkedin-app/user-service
    container_name: user-service
    networks:
      - linkedin-network
    depends_on:
      - user-db
      - discovery-server
      - kafka

  connections-service:
    image: shivmanoj/linkedin-app/connections-service
    container_name: connections-service
    networks:
      - linkedin-network
    depends_on:
      - connections-db
      - discovery-server
      - kafka

  api-gateway:
    image: shivmanoj/linkedin-app/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - linkedin-network
    depends_on:
      - discovery-server

networks:
  linkedin-network:

volumes:
  kafka_data:
  notification-db-data:
  user-db-data:
  posts-db-data:
  connections-db-data:
