version: "3.8"

services:
  post-db:
    image: postgres
    container_name: posts-db
    environment:
      - POSTGRES_DB=postsDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Manoj@123
    networks:
      - linkedin-network
    volumes:
      - posts-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_DB=usersDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Manoj@123
    networks:
      - linkedin-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  post-service:
    image: shivmanoj/linkedin-app/post-service
    container_name: post-service
    networks:
      - linkedin-network
    depends_on:
      - post-db

  user-service:
    image: shivmanoj/linkedin-app/user-service
    container_name: user-service
    networks:
      - linkedin-network
    depends_on:
      - user-db

networks:
  linkedin-network:

volumes:
  user-db-data:
  posts-db-data: