spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: connections-service
          uri: lb://CONNECTIONS-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

server:
  port: 8080

#Eureka config
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

jwt.secretKey: kjhsouLBLUYP38HLHLjljklbljnclakshlkewhliwvheichISHDLKSBDahefiunq34898lkqjn398rj
